### ISSUE TITLE
Crear Perfil

### ISSUE THREAD

**Issue by marcalmon** [chicasprogramando/api-chicasProgramando#19]
Validación y almacenamiento de datos ingresados ​​en el formulario para la creación del perfil.

- [X] Crear método `create` en `users_controller`
- [X] Validar en parametros

**Comment by elstr** [comment]
@marcalmon por lo que vi, valida automático los parametros recibidos según el esquema definido.
Password si es < a 6 chars te lo rebota, te rebota si skills está vacío y tiene algunas validaciones más. 

@giacastello
Deberíamos re ver esto? Qué se tiene que validar?
